---
name: WWW-Shorten-NotLong
version: 2.00
author:
  - 'Eric Hammond <ehammond@thinksome.com>'
  - |-
    Based almost entirely on WWW::Shorten::Shorl by Iain Truskett <spoon@cpan.org>
    which was based on WWW::MakeAShorterLink by Dave Cross <dave@dave.org.uk>
abstract: Perl interface to notlong.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  LWP: 5.75
  LWP::UserAgent: 2.023
  URI: 1.27
  WWW::Shorten: 0
  perl: 5.006
build_requires:
  Test::More: 0.47
provides:
  WWW::Shorten::NotLong:
    file: lib/WWW/Shorten/NotLong.pm
    version: 2.00
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
